name: Sync Fork with Upstream Repository

on:
  schedule:
    - cron: '0 * * * *'  # 每小时同步一次
  push:
    branches:
      - master  # 你可以修改为你想同步的分支

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Fork repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的历史记录（必须）

      # 2. Add upstream remote repository
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git
          git fetch upstream --prune  # 获取所有分支和删除上游已删除的分支

      # 3. Sync all branches
      - name: Sync branches
        run: |
          for branch in $(git branch -r | grep 'upstream/' | grep -v 'HEAD' | sed 's/upstream\///'); do
            git checkout $branch || git checkout -b $branch
            git pull upstream $branch
            git push origin $branch
          done

      # 4. Sync tags
      - name: Sync tags
        run: |
          git fetch upstream --tags
          git push origin --tags
